// Regular interface export
export interface Project {
  ID:number,
  id: string | number;
  name: string;
  desc: string;
  periode: string;
  feature: string;
  stack: string[];
  image: File | string;
  link: string;
  user_id: string;
}
export interface Experience {
  ID?: number;  // Optional because it's auto-generated by backend
  id?: string | number; // Optional for the same reason
  company: string;
  role: string;
  periode: string;
  contribution: string;
  stack: string | string[];
}

// Type export
export type ProjectFormData = Omit<Project, 'id'>;

// Another example of type export
export type ApiError = {
  message: string;
  status?: number;
  data?: any;
};