// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Project struct {
	ID          uuid.UUID
	Title       string
	Description string
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	ImageUrl    sql.NullString
	Stack       sql.NullString
	LinkGithub  sql.NullString
	UserID      uuid.NullUUID
	CreatedAt   sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt sql.NullTime
}
